### ISSUE TITLE
Endpräsentation im Zoom-Raum

### ISSUE THREAD

**Issue by lgehring** [lgehring/bl-predictor#64]
Hallo zusammen. Wir würden unsere Endpräsentation gerne wie bisher im regulären Zoom-Raum halten, da wir großteils noch keine Erfahrung mit BigBlueButton haben.
@coldfix @fsschneider @f-dangel

**Comment by f-dangel** [comment]
Hi zusammen. Kein Problem, dann verwenden wir einfach den Zoom-Link aus unseren Scrum-Meetings. Bis morgen.
