### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by SoccerCashUK** [lgehring/bl-predictor#65]
Hi when I run app the main display is different to yours
here is yours
 
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6e443447476c784f44516f47585577356c4a2f67697068792e676966](https://github.com/lgehring/bl-predictor/assets/43697092/9e97826e-ad56-429e-b640-304eac75e77d)
 and here is mine
![image](https://github.com/lgehring/bl-predictor/assets/43697092/ac36a038-d205-46af-a7b0-b740c9c0e1c7)
Not sure why.

When I download data does it save to crawled_data.csv ? as I don't see it saving to that file.
I1m running windows , with python

thanks James

**Comment by lgehring** [comment]
Hi James,
Thanks for your interest in our project.

I just installed the project from scratch myself and for me everything works out as expected. I see the UI as shown in the README.
Maybe you could try to use a clean virtual environment with Python 3.8.

When initially downloading data for a large timespan it can take quite some time; subsequent downloads should be significantly faster. For me, 2021-2022 took about 10 seconds.

All the best
lgehring

**Comment by SoccerCashUK** [comment]
Hi sorry to ask but how do i do clean virtual environment with Python.
Is possible to do other leagues

James

**Comment by lgehring** [comment]
Hi James,

you can follow [this guide](https://martinfritz.medium.com/work-with-multiple-versions-of-python-on-windows-10-eed1e5f52f07) to set up your virtual environment.

I suppose it should be possible to do other leagues. You can probably modify the code for in _crawler.py_ to access other data from [openliga.db](api.openligadb.de).

lgehring
